# fly.toml app configuration file generated for bloglist-cicd-fragrant-hill-2166 on 2025-04-27T21:23:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglist-cicd-fragrant-hill-2166'
primary_region = 'cdg'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

    [[http_service.machine_checks]]
      image = "curlimages/curl"
      entrypoint = ["/bin/sh", "-c"]
      command = ["curl -v http://[$FLY_TEST_MACHINE_IP]/health"]
      kill_signal = "SIGKILL"
      kill_timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

  [deploy]
  strategy = "canary"
  max_unavailable = 1
