name: Deployment Pipeline
env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(github.event.head_commit.message, '#skip') }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}
  TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend
        run: npm install || (echo "Install Backend" > fail.txt && exit 1)

      - name: Install Frontend
        working-directory: ./bloglist-frontend
        run: npm install || (echo "Install Frontend" > fail.txt && exit 1)

      - name: Lint Backend
        run: npm run eslint || (echo "Lint Backend" > fail.txt && exit 1)

      - name: Lint Frontend
        working-directory: ./bloglist-frontend
        run: npm run eslint || (echo "Lint Frontend" > fail.txt && exit 1)

      - name: Test Backend
        run: npm run test || (echo "Test Backend" > fail.txt && exit 1)

      - name: Test Frontend (Vitest)
        working-directory: ./bloglist-frontend
        run: npm run test || (echo "Test Frontend (Vitest)" > fail.txt && exit 1)

      - name: Build Frontend
        working-directory: ./bloglist-frontend
        run: npm run build || (echo "Build Frontend" > fail.txt && exit 1)
   
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Test Playwright
        run: npm run test:e2e || (echo "Test Playwright" > fail.txt && exit 1)

      - name: Setup Fly
        if: ${{ env.SHOULD_DEPLOY }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        if: ${{ env.SHOULD_DEPLOY }}
        run: flyctl deploy --remote-only || (echo "Deploy to Fly" > fail.txt && exit 1)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Upload fail.txt if something failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-step
          path: fail.txt
          if-no-files-found: ignore

  auto_tag:
    needs: [deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.SHOULD_DEPLOY == 'true' }}

      - name: Version up and push tag
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 1.0.0

  notify:
    needs: [deployment_pipeline, auto_tag]
    runs-on: ubuntu-22.04
    steps:
      - name: Try recover any failed step
        if: failure()
        uses: actions/download-artifact@v4
        with:
          name: failed-step

      - name: Parse the failed step
        if: failure()
        run: echo "FAILED_STEP=$(cat fail.txt)" >> $GITHUB_ENV

      - name: Notify Successful Build
        uses: stegzilla/discord-notify@v2
        if: ${{ success() && env.SHOULD_DEPLOY }}
        with:
          username: The GitHub Times
          title: New Blog List build deployed!
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          include_image: false
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          colour: #00FF00
          message: |
            - **Site:** [Blog List App](https://bloglist-cicd-fragrant-hill-2166.fly.dev)
            - **Commit Author**: ${{ github.event.head_commit.author.username }}
            - **Commit**: [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})

            **Severity:** Information

      - name: Notify Failed Build
        uses: stegzilla/discord-notify@v2
        if: failure()
        with:
          username: The GitHub Times
          title: Blog List build deployment failed!
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          include_image: false
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          colour: #FF0000
          message: |
            - **Failed Step:** ${{ env.FAILED_STEP }}
            - **Who to blame:** ${{ github.event.head_commit.author.username }}
            - **Commit:** [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})

            **Severity:** Error
